#pragma once
#define READ_RGBA(set, a, b, c) a = set[b].asRGBA(c)

class CHudColoursNew {
public:
	// Original game colors.
	CRGBA HUD_COLOUR_PURE_WHITE;
	CRGBA HUD_COLOUR_WHITE;
	CRGBA HUD_COLOUR_BLACK;
	CRGBA HUD_COLOUR_RED;
	CRGBA HUD_COLOUR_REDLIGHT;
	CRGBA HUD_COLOUR_REDDARK;
	CRGBA HUD_COLOUR_GREEN;
	CRGBA HUD_COLOUR_GREENLIGHT;
	CRGBA HUD_COLOUR_GREENDARK;
	CRGBA HUD_COLOUR_BLUE;
	CRGBA HUD_COLOUR_BLUELIGHT;
	CRGBA HUD_COLOUR_BLUEDARK;
	CRGBA HUD_COLOUR_ORANGE;
	CRGBA HUD_COLOUR_ORANGELIGHT;
	CRGBA HUD_COLOUR_ORANGEDARK;
	CRGBA HUD_COLOUR_PURPLE;
	CRGBA HUD_COLOUR_PURPLELIGHT;
	CRGBA HUD_COLOUR_PURPLEDARK;
	CRGBA HUD_COLOUR_GREY;
	CRGBA HUD_COLOUR_GREYDARK;
	CRGBA HUD_COLOUR_YELLOW;
	CRGBA HUD_COLOUR_YELLOWLIGHT;
	CRGBA HUD_COLOUR_YELLOWDARK;
	CRGBA HUD_COLOUR_PINK;

	// Classic hud colors.
	CRGBA HUD_COLOUR_CLOCK, HUD_COLOUR_CLOCK_TEMP;
	CRGBA HUD_COLOUR_CASH, HUD_COLOUR_CASH_TEMP;
	CRGBA HUD_COLOUR_HEALTH, HUD_COLOUR_HEALTH_TEMP;
	CRGBA HUD_COLOUR_ARMOUR, HUD_COLOUR_ARMOUR_TEMP;
	CRGBA HUD_COLOUR_BREATH, HUD_COLOUR_BREATH_TEMP;
	CRGBA HUD_COLOUR_WEAPON_ICON, HUD_COLOUR_WEAPON_ICON_TEMP;
	CRGBA HUD_COLOUR_AMMO, HUD_COLOUR_AMMO_TEMP;
	CRGBA HUD_COLOUR_WANTED_N, HUD_COLOUR_WANTED_A, HUD_COLOUR_WANTED_N_TEMP, HUD_COLOUR_WANTED_A_TEMP;
	CRGBA HUD_COLOUR_ZONE_NAME, HUD_COLOUR_ZONE_NAME_TEMP;
	CRGBA HUD_COLOUR_VEHICLE_NAME, HUD_COLOUR_VEHICLE_NAME_TEMP;
	CRGBA HUD_COLOUR_RADIO_NAME_N, HUD_COLOUR_RADIO_NAME_A, HUD_COLOUR_RADIO_NAME_N_TEMP, HUD_COLOUR_RADIO_NAME_A_TEMP;
	CRGBA HUD_COLOUR_HELP_TEXT, HUD_COLOUR_HELP_TEXT_TEMP;
	CRGBA HUD_COLOUR_HELP_BOX, HUD_COLOUR_HELP_BOX_TEMP;
	CRGBA HUD_COLOUR_SUBTITLES, HUD_COLOUR_SUBTITLES_TEMP;
	CRGBA HUD_COLOUR_WASTED, HUD_COLOUR_WASTED_TEMP;
	CRGBA HUD_COLOUR_BUSTED, HUD_COLOUR_BUSTED_TEMP;
	CRGBA HUD_COLOUR_MISSION_RESULT, HUD_COLOUR_MISSION_RESULT_TEMP;
	CRGBA HUD_COLOUR_MISSION_TITLE, HUD_COLOUR_MISSION_TITLE_TEMP;
	CRGBA HUD_COLOUR_DAMAGE, HUD_COLOUR_DAMAGE_TEMP;

public:
	CHudColoursNew();

	void Initialise();
	void Shutdown();

public:
	static void __fastcall ReadDefaultColors(CRGBA *color, int);
};

extern CHudColoursNew HudColourNew;
